name: ai_mutfak_asistani
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.6.0
  flutter_tts: ^3.8.5
  shared_preferences: ^2.3.2
  google_generative_ai: ^0.4.7
  image_picker: ^1.0.4
  google_mlkit_image_labeling: ^0.14.1
  share_plus: ^12.0.1
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png

# DİKKAT: flutter_launcher_icons satırı EN SOLA dayalı olmalı!
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon.png"
  min_sdk_android: 21